dist: trusty
sudo: required

language: node_js
node_js:
    - '11'
    - '10'
    - '8'

cache:
    yarn: true
    directories:
        - 'node_modules'

notifications:
    email: false

script:
    - yarn build
    - yarn test
